that the problem

diff --git a/.github/workflows/docker_tests.yml b/.github/workflows/docker_tests.yml
--- a/.github/workflows/docker_tests.yml
+++ b/.github/workflows/docker_tests.yml
@@ -77,12 +77,12 @@ jobs:
 
     runs-on: [self-hosted, docker-tests]
 
-    # if: github.event_name != 'pull_request'
+    if: github.event_name != 'pull_request'
 
     environment:
       name: docker_tests
 
-    # needs: build_docker_images
+    needs: build_docker_images
 
     steps:
       - name: Checkout code
@@ -93,54 +93,54 @@ jobs:
         with:
           python-version: 3.9
 
-      # - name: Install requirements
-      #   run: |
-      #     cd headless
-      #     pip install -r requirements.txt
+      - name: Install requirements
+        run: |
+          cd headless
+          pip install -r requirements.txt
 
-      # - name: SHARE_DIR env variable
-      #   run: |
-      #     mkdir -p $HOME/nfs/dir
-      #     echo "SHARE_DIR=$HOME/nfs/dir" >> $GITHUB_ENV
-      #     echo "GENAI_KEY=${{ secrets.GENAI_KEY }}" >> $GITHUB_ENV
+      - name: SHARE_DIR env variable
+        run: |
+          mkdir -p $HOME/nfs/dir
+          echo "SHARE_DIR=$HOME/nfs/dir" >> $GITHUB_ENV
+          echo "GENAI_KEY=${{ secrets.GENAI_KEY }}" >> $GITHUB_ENV
 
-      # - name: Restart Model Bazaar Job
-      #   run: |
-      #     version="${{ needs.build_docker_images.outputs.version }}"
-      #     echo "Restarting the model bazaar with the: $version"
-      #     python3 -m headless.restart_modelbazaar --version "$version"
+      - name: Restart Model Bazaar Job
+        run: |
+          version="${{ needs.build_docker_images.outputs.version }}"
+          echo "Restarting the model bazaar with the: $version"
+          python3 -m headless.restart_modelbazaar --version "$version"
 
-      # - name: Generate random run name
-      #   id: random-run-name
-      #   run: |
-      #     echo "::set-output name=name::test_$(python3 -c "import secrets; print(secrets.token_urlsafe(8))")"
+      - name: Generate random run name
+        id: random-run-name
+        run: |
+          echo "::set-output name=name::test_$(python3 -c "import secrets; print(secrets.token_urlsafe(8))")"
 
-      # - name: Delay before running tests
-      #   run: sleep 150 # Wait for 2 1/2 minutes (150 seconds)
+      - name: Delay before running tests
+        run: sleep 150 # Wait for 2 1/2 minutes (150 seconds)
 
-      # - name: Run tests
-      #   run: |
-      #     python3 -m headless.run_locally --base-url ${{ secrets.BASE_URL }} --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag NDB --on-prem --generation
-      #     python3 -m headless.run_locally --base-url ${{ secrets.BASE_URL }} --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag UDT
-      #     python3 -m headless.run_locally --base-url ${{ secrets.BASE_URL }} --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag UDT_DATAGEN
+      - name: Run tests
+        run: |
+          python3 -m headless.run_locally --base-url ${{ secrets.BASE_URL }} --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag NDB --on-prem --generation
+          python3 -m headless.run_locally --base-url ${{ secrets.BASE_URL }} --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag UDT
+          python3 -m headless.run_locally --base-url ${{ secrets.BASE_URL }} --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag UDT_DATAGEN
 
-      # - name: Cleanup SHARE_DIR Folder
-      #   if: always()
-      #   run: |
-      #     echo "Cleaning up SHARE_DIR folder..."
-      #     rm -rf $HOME/nfs/dir
+      - name: Cleanup SHARE_DIR Folder
+        if: always()
+        run: |
+          echo "Cleaning up SHARE_DIR folder..."
+          rm -rf $HOME/nfs/dir
 
-      # - name: Test Next.js frontend
-      #   run: |
-      #     BASE_URL_WITHOUT_API=$(echo "${{ secrets.BASE_URL }}" | sed 's/\/api\/\?$//')
-      #     echo "Testing frontend at $BASE_URL_WITHOUT_API"
-      #     curl -f "$BASE_URL_WITHOUT_API" || exit 1
+      - name: Test Next.js frontend
+        run: |
+          BASE_URL_WITHOUT_API=$(echo "${{ secrets.BASE_URL }}" | sed 's/\/api\/\?$//')
+          echo "Testing frontend at $BASE_URL_WITHOUT_API"
+          curl -f "$BASE_URL_WITHOUT_API" || exit 1
       
-      # # This is to clean up local docker builds to free up storage.
-      # - name: Cleanup Docker after build
-      #   if: always() # Run this step regardless of success or failure
-      #   run: |
-      #     docker system prune -af --volumes
+      # This is to clean up local docker builds to free up storage.
+      - name: Cleanup Docker after build
+        if: always() # Run this step regardless of success or failure
+        run: |
+          docker system prune -af --volumes
 
       - name: Install git
         if: always()
@@ -168,58 +168,58 @@ jobs:
           cd thirdai_platform/database/alembic/versions
           ls
 
-      # - name: Install requirements
-      #   if: always()
-      #   run: |
-      #     cd thirdai_platform
-      #     pip install -r requirements.txt
+      - name: Install requirements
+        if: always()
+        run: |
+          cd thirdai_platform
+          pip install -r requirements.txt
 
-      # - name: Revert Back to original alembic version
-      #   if: always()
-      #   env:
-      #     DATABASE_URI: ${{ secrets.DATABASE_URI }}
-      #   run: |
-      #     cd thirdai_platform
-      #     alembic downgrade ${{ steps.version.outputs.alembic_version }}
+      - name: Revert Back to original alembic version
+        if: always()
+        env:
+          DATABASE_URI: ${{ secrets.DATABASE_URI }}
+        run: |
+          cd thirdai_platform
+          alembic downgrade ${{ steps.version.outputs.alembic_version }}
 
-      # - name: Read Nomad ACL Token
-      #   if: always()
-      #   id: read_nomad_token
-      #   run: |
-      #     TOKEN_FILE="/opt/thirdai_platform/nomad_data/management_token.txt"
-      #     if [ -f "$TOKEN_FILE" ]; then
-      #       NOMAD_TOKEN=$(grep 'Secret ID' "$TOKEN_FILE" | awk '{print $NF}')
-      #       echo "::add-mask::$NOMAD_TOKEN"  # Masks the token in logs
-      #       echo "NOMAD_TOKEN=$NOMAD_TOKEN" >> $GITHUB_ENV
-      #     else
-      #       echo "Nomad token file not found at $TOKEN_FILE"
-      #       exit 1
-      #     fi
+      - name: Read Nomad ACL Token
+        if: always()
+        id: read_nomad_token
+        run: |
+          TOKEN_FILE="/opt/thirdai_platform/nomad_data/management_token.txt"
+          if [ -f "$TOKEN_FILE" ]; then
+            NOMAD_TOKEN=$(grep 'Secret ID' "$TOKEN_FILE" | awk '{print $NF}')
+            echo "::add-mask::$NOMAD_TOKEN"  # Masks the token in logs
+            echo "NOMAD_TOKEN=$NOMAD_TOKEN" >> $GITHUB_ENV
+          else
+            echo "Nomad token file not found at $TOKEN_FILE"
+            exit 1
+          fi
 
-      # - name: Set SKIP_JOBS environment variables
-      #   if: always()
-      #   run: |
-      #     ENABLE_SKIP_JOBS="true"  # Set to "false" to disable skipping
-      #     SKIP_JOBS="autoscaler,traefik,telemetry"
-      #     echo "ENABLE_SKIP_JOBS=$ENABLE_SKIP_JOBS" >> $GITHUB_ENV
-      #     echo "SKIP_JOBS=$SKIP_JOBS" >> $GITHUB_ENV
+      - name: Set SKIP_JOBS environment variables
+        if: always()
+        run: |
+          ENABLE_SKIP_JOBS="true"  # Set to "false" to disable skipping
+          SKIP_JOBS="autoscaler,traefik,telemetry"
+          echo "ENABLE_SKIP_JOBS=$ENABLE_SKIP_JOBS" >> $GITHUB_ENV
+          echo "SKIP_JOBS=$SKIP_JOBS" >> $GITHUB_ENV
 
-      # - name: Run fetch_nomad_logs.sh script
-      #   if: always()
-      #   env:
-      #     NOMAD_TOKEN: ${{ env.NOMAD_TOKEN }}
-      #     SKIP_JOBS: ${{ env.SKIP_JOBS }}
-      #     ENABLE_SKIP_JOBS: ${{ env.ENABLE_SKIP_JOBS }}
-      #   run: |
-      #     bash local_setup/fetch_nomad_logs.sh
+      - name: Run fetch_nomad_logs.sh script
+        if: always()
+        env:
+          NOMAD_TOKEN: ${{ env.NOMAD_TOKEN }}
+          SKIP_JOBS: ${{ env.SKIP_JOBS }}
+          ENABLE_SKIP_JOBS: ${{ env.ENABLE_SKIP_JOBS }}
+        run: |
+          bash local_setup/fetch_nomad_logs.sh
 
-      # - name: Grabage collect the jobs
-      #   if: always()
-      #   env:
-      #     NOMAD_TOKEN: ${{ env.NOMAD_TOKEN }}
-      #   run: |
-      #     NOMAD_PATH=$(which nomad)
-      #     $NOMAD_PATH system gc
+      - name: Grabage collect the jobs
+        if: always()
+        env:
+          NOMAD_TOKEN: ${{ env.NOMAD_TOKEN }}
+        run: |
+          NOMAD_PATH=$(which nomad)
+          $NOMAD_PATH system gc
 
   delete_docker_images:
     runs-on: ubuntu-latest
