vague checking

diff --git a/.github/workflows/docker_tests.yml b/.github/workflows/docker_tests.yml
--- a/.github/workflows/docker_tests.yml
+++ b/.github/workflows/docker_tests.yml
@@ -71,19 +71,62 @@ jobs:
         run: |
           docker system prune -af --volumes
 
-  restart_modelbazaar:
+  # restart_modelbazaar:
+  #   runs-on: self-hosted
+  #   environment:
+  #     name: docker_tests
+    
+  #   # Concurrency control to ensure exclusivity across workflows
+  #   concurrency:
+  #     group: critical-workflow-lock
+  #     cancel-in-progress: false
+
+  #   if: github.event_name != 'pull_request'
+
+  #   needs: build_docker_images
+
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
+
+  #     - name: Set up Python 3.9
+  #       uses: actions/setup-python@v2
+  #       with:
+  #         python-version: 3.9
+
+  #     - name: Install requirements
+  #       run: |
+  #         cd headless
+  #         pip install -r requirements.txt
+
+  #     - name: SHARE_DIR env variable
+  #       run: |
+  #         mkdir -p $HOME/nfs/dir
+  #         echo "SHARE_DIR=$HOME/nfs/dir" >> $GITHUB_ENV
+
+  #     - name: Restart Model Bazaar Job
+  #       run: |
+  #         version="${{ needs.build_docker_images.outputs.version }}"
+  #         echo "Restarting the model bazaar with the: $version"
+  #         python3 -m headless.restart_modelbazaar --version "$version"
+
+  test:
+    strategy:
+      fail-fast: false
+
     runs-on: self-hosted
+
+    # # Concurrency control to ensure exclusivity across workflows
+    # concurrency:
+    #   group: critical-workflow-lock
+    #   cancel-in-progress: false
+
+    # if: github.event_name != 'pull_request'
+
     environment:
       name: docker_tests
-    
-    # Concurrency control to ensure exclusivity across workflows
-    concurrency:
-      group: critical-workflow-lock
-      cancel-in-progress: false
 
-    if: github.event_name != 'pull_request'
-
-    needs: build_docker_images
+    # needs: build_docker_images
 
     steps:
       - name: Checkout code
@@ -104,56 +147,19 @@ jobs:
           mkdir -p $HOME/nfs/dir
           echo "SHARE_DIR=$HOME/nfs/dir" >> $GITHUB_ENV
 
-      - name: Restart Model Bazaar Job
-        run: |
-          version="${{ needs.build_docker_images.outputs.version }}"
-          echo "Restarting the model bazaar with the: $version"
-          python3 -m headless.restart_modelbazaar --version "$version"
-
-  test:
-    strategy:
-      fail-fast: false
-
-    runs-on: self-hosted
-
-    # Concurrency control to ensure exclusivity across workflows
-    concurrency:
-      group: critical-workflow-lock
-      cancel-in-progress: false
-
-    if: github.event_name != 'pull_request'
-
-    environment:
-      name: docker_tests
-
-    needs: restart_modelbazaar
-
-    steps:
-      - name: Delay before running tests
-        run: sleep 150 # Wait for 2 1/2 minutes (150 seconds)
-
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up Python 3.9
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.9
-
-      - name: Install requirements
-        run: |
-          cd headless
-          pip install -r requirements.txt
+      # - name: Restart Model Bazaar Job
+      #   run: |
+      #     version="${{ needs.build_docker_images.outputs.version }}"
+      #     echo "Restarting the model bazaar with the: $version"
+      #     python3 -m headless.restart_modelbazaar --version "$version"
 
       - name: Generate random run name
         id: random-run-name
         run: |
           echo "::set-output name=name::test_$(python3 -c "import secrets; print(secrets.token_urlsafe(8))")"
 
-      - name: Create Directories for Share and Test
-        run: |
-          mkdir -p $HOME/nfs/dir
-          echo "SHARE_DIR=$HOME/nfs/dir" >> $GITHUB_ENV
+      # - name: Delay before running tests
+      #   run: sleep 150 # Wait for 2 1/2 minutes (150 seconds)
 
       - name: Run tests
         run: |
@@ -179,36 +185,17 @@ jobs:
         run: |
           docker system prune -af --volumes
 
-  restore_original_alembic_version:
-    runs-on: self-hosted
-
-    # Concurrency control to ensure exclusivity across workflows
-    concurrency:
-      group: critical-workflow-lock
-      cancel-in-progress: false
-
-    # needs: test
-
-    # This condition ensures that the job runs only if the branch is not 'main' and it's not a pull request.
-    # if: github.ref != 'refs/heads/main' && github.event_name != 'pull_request'
-
-    environment:
-      name: docker_tests
-
-    steps:
-      - name: Set up Python 3.9
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.9
-
       - name: Install git
+        if: always()
         run: |
           pip install gitpython
 
       - name: Checkout current branch
+        if: always()
         uses: actions/checkout@v3
 
       - name: Latest alembic version in main
+        if: always()
         id: version
         run: |
           alembic_version=$(python alembic_version.py)
@@ -216,21 +203,110 @@ jobs:
           echo "$alembic_version"
 
       - name: Install requirements
+        if: always()
         run: |
           cd thirdai_platform
           pip install -r requirements.txt
 
       - name: Revert Back to original alembic version
+        if: always()
         env:
           DATABASE_URI: ${{ secrets.DATABASE_URI }}
         run: |
           cd thirdai_platform
           alembic downgrade ${{ steps.version.outputs.alembic_version }}
-      
-      - name: Cleanup Docker after build
-        if: always() # Run this step regardless of success or failure
+
+      - name: Read Nomad ACL Token
+        if: always()
+        id: read_nomad_token
         run: |
-          docker system prune -af --volumes
+          TOKEN_FILE="/opt/thirdai_platform/nomad_data/management_token.txt"
+          if [ -f "$TOKEN_FILE" ]; then
+            NOMAD_TOKEN=$(grep 'Secret ID' "$TOKEN_FILE" | awk '{print $NF}')
+            echo "::add-mask::$NOMAD_TOKEN"  # Masks the token in logs
+            echo "NOMAD_TOKEN=$NOMAD_TOKEN" >> $GITHUB_ENV
+          else
+            echo "Nomad token file not found at $TOKEN_FILE"
+            exit 1
+          fi
+
+      - name: Set SKIP_JOBS environment variables
+        if: always()
+        run: |
+          ENABLE_SKIP_JOBS="true"  # Set to "false" to disable skipping
+          SKIP_JOBS="redis-server,autoscaler,traefik,telemetry"
+          echo "ENABLE_SKIP_JOBS=$ENABLE_SKIP_JOBS" >> $GITHUB_ENV
+          echo "SKIP_JOBS=$SKIP_JOBS" >> $GITHUB_ENV
+
+      - name: Run fetch_nomad_logs.sh script
+        if: always()
+        env:
+          NOMAD_TOKEN: ${{ env.NOMAD_TOKEN }}
+          SKIP_JOBS: ${{ env.SKIP_JOBS }}
+          ENABLE_SKIP_JOBS: ${{ env.ENABLE_SKIP_JOBS }}
+        run: |
+          bash local_setup/fetch_nomad_logs.sh
+
+      - name: Grabage collect the jobs
+        if: always()
+        env:
+          NOMAD_TOKEN: ${{ env.NOMAD_TOKEN }}
+        run: |
+          NOMAD_PATH=$(which nomad)
+          $NOMAD_PATH system gc
+
+  # restore_original_alembic_version:
+  #   runs-on: self-hosted
+
+  #   # Concurrency control to ensure exclusivity across workflows
+  #   concurrency:
+  #     group: critical-workflow-lock
+  #     cancel-in-progress: false
+
+  #   # needs: test
+
+  #   # This condition ensures that the job runs only if the branch is not 'main' and it's not a pull request.
+  #   # if: github.ref != 'refs/heads/main' && github.event_name != 'pull_request'
+
+  #   environment:
+  #     name: docker_tests
+
+  #   steps:
+  #     - name: Set up Python 3.9
+  #       uses: actions/setup-python@v2
+  #       with:
+  #         python-version: 3.9
+
+  #     - name: Install git
+  #       run: |
+  #         pip install gitpython
+
+  #     - name: Checkout current branch
+  #       uses: actions/checkout@v3
+
+  #     - name: Latest alembic version in main
+  #       id: version
+  #       run: |
+  #         alembic_version=$(python alembic_version.py)
+  #         echo "::set-output name=alembic_version::$alembic_version"
+  #         echo "$alembic_version"
+
+  #     - name: Install requirements
+  #       run: |
+  #         cd thirdai_platform
+  #         pip install -r requirements.txt
+
+  #     - name: Revert Back to original alembic version
+  #       env:
+  #         DATABASE_URI: ${{ secrets.DATABASE_URI }}
+  #       run: |
+  #         cd thirdai_platform
+  #         alembic downgrade ${{ steps.version.outputs.alembic_version }}
+      
+  #     - name: Cleanup Docker after build
+  #       if: always() # Run this step regardless of success or failure
+  #       run: |
+  #         docker system prune -af --volumes
 
   delete_docker_images:
     runs-on: ubuntu-latest
@@ -259,56 +335,56 @@ jobs:
           echo "Deleting Docker images for version: $version"
           python3 docker_remove.py -b docker_tests --version "$version" --client_id ${{ secrets.APPLICATION_ID }} --tenant_id ${{ secrets.TENANT_ID }} --secret ${{ secrets.SECRET }} --config config.yaml
 
-  fetch_nomad_job_logs:
-    runs-on: self-hosted
+  # fetch_nomad_job_logs:
+  #   runs-on: self-hosted
 
-    environment:
-      name: docker_tests
+  #   environment:
+  #     name: docker_tests
 
-    # Concurrency control to ensure exclusivity across workflows
-    concurrency:
-      group: critical-workflow-lock
-      cancel-in-progress: false
+  #   # Concurrency control to ensure exclusivity across workflows
+  #   concurrency:
+  #     group: critical-workflow-lock
+  #     cancel-in-progress: false
 
-    needs: test
+  #   needs: test
 
-    if: always() && github.event_name != 'pull_request'
+  #   if: always() && github.event_name != 'pull_request'
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Read Nomad ACL Token
-        id: read_nomad_token
-        run: |
-          TOKEN_FILE="/opt/thirdai_platform/nomad_data/management_token.txt"
-          if [ -f "$TOKEN_FILE" ]; then
-            NOMAD_TOKEN=$(grep 'Secret ID' "$TOKEN_FILE" | awk '{print $NF}')
-            echo "::add-mask::$NOMAD_TOKEN"  # Masks the token in logs
-            echo "NOMAD_TOKEN=$NOMAD_TOKEN" >> $GITHUB_ENV
-          else
-            echo "Nomad token file not found at $TOKEN_FILE"
-            exit 1
-          fi
+  #     - name: Read Nomad ACL Token
+  #       id: read_nomad_token
+  #       run: |
+  #         TOKEN_FILE="/opt/thirdai_platform/nomad_data/management_token.txt"
+  #         if [ -f "$TOKEN_FILE" ]; then
+  #           NOMAD_TOKEN=$(grep 'Secret ID' "$TOKEN_FILE" | awk '{print $NF}')
+  #           echo "::add-mask::$NOMAD_TOKEN"  # Masks the token in logs
+  #           echo "NOMAD_TOKEN=$NOMAD_TOKEN" >> $GITHUB_ENV
+  #         else
+  #           echo "Nomad token file not found at $TOKEN_FILE"
+  #           exit 1
+  #         fi
 
-      - name: Set SKIP_JOBS environment variables
-        run: |
-          ENABLE_SKIP_JOBS="true"  # Set to "false" to disable skipping
-          SKIP_JOBS="redis-server,autoscaler,traefik,telemetry"
-          echo "ENABLE_SKIP_JOBS=$ENABLE_SKIP_JOBS" >> $GITHUB_ENV
-          echo "SKIP_JOBS=$SKIP_JOBS" >> $GITHUB_ENV
+  #     - name: Set SKIP_JOBS environment variables
+  #       run: |
+  #         ENABLE_SKIP_JOBS="true"  # Set to "false" to disable skipping
+  #         SKIP_JOBS="redis-server,autoscaler,traefik,telemetry"
+  #         echo "ENABLE_SKIP_JOBS=$ENABLE_SKIP_JOBS" >> $GITHUB_ENV
+  #         echo "SKIP_JOBS=$SKIP_JOBS" >> $GITHUB_ENV
 
-      - name: Run fetch_nomad_logs.sh script
-        env:
-          NOMAD_TOKEN: ${{ env.NOMAD_TOKEN }}
-          SKIP_JOBS: ${{ env.SKIP_JOBS }}
-          ENABLE_SKIP_JOBS: ${{ env.ENABLE_SKIP_JOBS }}
-        run: |
-          bash local_setup/fetch_nomad_logs.sh
+  #     - name: Run fetch_nomad_logs.sh script
+  #       env:
+  #         NOMAD_TOKEN: ${{ env.NOMAD_TOKEN }}
+  #         SKIP_JOBS: ${{ env.SKIP_JOBS }}
+  #         ENABLE_SKIP_JOBS: ${{ env.ENABLE_SKIP_JOBS }}
+  #       run: |
+  #         bash local_setup/fetch_nomad_logs.sh
 
-      - name: Grabage collect the jobs
-        env:
-          NOMAD_TOKEN: ${{ env.NOMAD_TOKEN }}
-        run: |
-          NOMAD_PATH=$(which nomad)
-          $NOMAD_PATH system gc
+  #     - name: Grabage collect the jobs
+  #       env:
+  #         NOMAD_TOKEN: ${{ env.NOMAD_TOKEN }}
+  #       run: |
+  #         NOMAD_PATH=$(which nomad)
+  #         $NOMAD_PATH system gc
