cleanup

diff --git a/.github/workflows/integration_testing.yml b/.github/workflows/integration_testing.yml
--- a/.github/workflows/integration_testing.yml
+++ b/.github/workflows/integration_testing.yml
@@ -20,6 +20,14 @@ on:
         description: "Docker registry password for the branch image encoded in base64"
         required: true
         type: string
+      email:
+        description: "Global admin email ID"
+        type: string
+        default: gautam@thirdai.com
+      password:
+        description: "Global admin password"
+        type: string
+        default: password
     secrets:
       AWS_ACCESS_KEY_ID:
         description: "AWS access key id"
@@ -29,12 +37,6 @@ on:
         required: true
       HOST_MACHINE_PRIVATE_KEY:
         description: "server machine's private key hosted on AWS"
-        required: true
-      EMAIL:
-        description: "Global admin email ID"
-        required: true
-      PASSWORD:
-        description: "Global admin password"
         required: true
       GENAI_KEY:
         description: "GenAI key"
@@ -57,7 +59,7 @@ jobs:
   setup_the_ec2_instances:
     runs-on: ubuntu-latest-8-cores
     outputs:
-      server_machine_public_ip: ${{ steps.host_machine.outputs.public_ip }}
+      server_machine_public_ip: ${{ steps.host_machine1.outputs.public_ip }}
       task_runner_token: ${{ steps.task_runner.outputs.token }}
     steps:
       - name: Decode docker registry password
@@ -71,70 +73,144 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1     # ec2-instances are in this region
       
-      # These instances already have the aws configured to pull thirdai-packages from the s3 bucket
+      # JSON data of Host_machine secret:
+      # Host_machine1 = {
+      #   "instance_id": "i-sdsdjsdbis",
+      #   "ssh_username": "ubuntu",
+      #   "identity_key": "sdonsd"      # Corresponding public-key should be added in the authorized_hosts file in the host_machine1
+      # }
+      # Host_machine2 = {
+      #   "instance_id": "i-safdfsasds",
+      #   "ssh_username": "ubuntu"
+      # }
+      - name: Fetch the host machine details
+        run: |
+          # Don't use (Double-quotes) around secrets.HOST_MACHINE1 otherwise jq won't be able to parse it because all key, value are also needed to wrapped around (double-quotes)
+          echo '${{ secrets.HOST_MACHINE1 }}' > host_machine1.json
+          echo '${{ secrets.HOST_MACHINE2 }}' > host_machine2.json
+
+          # instance_id
+          echo "host_machine1_instance_id=$(jq -r '.instance_id' host_machine1.json)" >> $GITHUB_ENV
+          echo "host_machine2_instance_id=$(jq -r '.instance_id' host_machine1.json)" >> $GITHUB_ENV
+          
+      # Regarding instances:
+      #   - Server node (Host machine1) have the aws configured to pull images from s3 bucket
+      #   - yq installed to change the config.yml file. sudo snap install yq --channel=v3/stable). Don't add repository ppa:rmescandon/yq to install yq. It is causing `sudo apt-get update` to fail.
+      #   - Host_machine1 is already configured to have ssh-access to the host_machine2 (client node)
+      #   - ndb_enterprise_license.json file is already present on the machine at the home directory
       - name: start the ec2-instance
         run: |
-          aws ec2 start-instances --instance-ids i-0d7c02e319be52e71 i-066bb0f7bfb7ef7a3
+          aws ec2 start-instances --instance-ids ${{ env.host_machine1_instance_id }} ${{ env.host_machine2_instance_id }}
       
-      - name: Wait for EC2 to be running
+      - name: Wait for EC2 instances to be running
         run: |
-          echo "Waiting for EC2 instance to start..."
-          sleep 30
+          max_attempts=10
+          attempts=0
+          while [ $attempts -lt $max_attempts ]; do
+            host_machine1_state=$(aws ec2 describe-instances --instance-ids ${{ env.host_machine1_instance_id }} --query "Reservations[].Instances[].[State.Name]" --output text)
+            host_machine2_state=$(aws ec2 describe-instances --instance-ids ${{ env.host_machine2_instance_id }} --query "Reservations[].Instances[].[State.Name]" --output text)
 
-      - name: Fetch the public ip of the server machine
-        id: host_machine
+            if [ "$host_machine1_state" == "running" ] && [ "$host_machine2_state" == "running" ]; then
+              break
+            fi
+
+            attempts=$((attempts + 1))
+            
+            # sleep for 5 seconds
+            sleep 5
+          done
+
+          if [ $attempts -ge $max_attempts ]; then
+            echo "Maximum attempts reached. Unable to start machine(s). Exiting..."
+            exit 1
+          fi
+
+      - name: Fetch the public/private IP & ssh-username of the host machine 1
+        id: host_machine1
         run: |
-          PUBLIC_IP=$(aws ec2 describe-instances \
-              --instance-ids i-0d7c02e319be52e71 \
-              --query "Reservations[0].Instances[0].PublicIpAddress" \
+          host_machine1_ips=$(aws ec2 describe-instances \
+              --instance-ids ${{ env.host_machine1_instance_id }} \
+              --query "Reservations[0].Instances[0].[PublicIpAddress, PrivateIpAddress]" \
               --output text)
-          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT
+
+          # IPs
+          echo "public_ip=$(echo host_machine1_ips | awk '{print $1}')" >> $GITHUB_OUTPUT
+          echo "private_ip=$(echo host_machine1_ips | awk '{print $2}')" >> $GITHUB_OUTPUT
+
+          # ssh_username
+          echo "ssh_username=$(jq -r '.ssh_username' host_machine1.json)" >> $GITHUB_OUTPUT
+
+      - name: Fetch the public/private IP & ssh-username of the host machine 2
+        id: host_machine2
+        run: |
+          host_machine2_ips=$(aws ec2 describe-instances \
+              --instance-ids ${{ env.host_machine2_instance_id }} \
+              --query "Reservations[0].Instances[0].[PublicIpAddress, PrivateIpAddress]" \
+              --output text)
+          
+          # IPs
+          echo "public_ip=$(echo host_machine2_ips | awk '{print $1}')" >> $GITHUB_OUTPUT
+          echo "private_ip=$(echo host_machine2_ips | awk '{print $2}')">> $GITHUB_OUTPUT
+          
+          # ssh-username
+          echo "ssh_username=$(jq -r '.ssh_username' host_machine2.json)" >> $GITHUB_OUTPUT
       
       - name: Create an identity file for ssh-login
         run: |
-          echo "${{ secrets.HOST_MACHINE_PRIVATE_KEY }}" > /tmp/id_rsa
+          echo $(jq '.identity_key' host_machine1.json | tr -d '"') | sed 's/\\n/\n/g' > /tmp/id_rsa
           chmod 600 /tmp/id_rsa
-
-      - name: Download the package and run driver.sh
+      
+      - name: Check if license file is present on the host machine1
         run: |
-          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=120 -o ServerAliveCountMax=25 -i /tmp/id_rsa ubuntu@${{ steps.host_machine.outputs.public_ip }} <<EOF        
-            aws s3 cp s3://thirdai-corp-public/ThirdAI-Platform-latest-release/${{ inputs.tarball_filename }} /home/ubuntu/
+          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=120 -o ServerAliveCountMax=25 -i /tmp/id_rsa ${{ steps.host_machine1.outputs.ssh_username }}@${{ steps.host_machine1.outputs.public_ip }} <<EOF
+            if [ ! -f "\$root_dir/ndb_enterprise_license.json" ]; then
+              echo "ndb_enterprise_license.json is not at the directory \$root_dir"
+              exit 1
+            fi
+          EOF
+
+      - name: Download the package and run driver.sh on host_machine1
+        run: |
+          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=120 -o ServerAliveCountMax=25 -i /tmp/id_rsa ${{ steps.host_machine1.outputs.ssh_username }}@${{ steps.host_machine1.outputs.public_ip }} <<EOF        
+            root_dir=/home/${{ steps.host_machine1.outputs.ssh_username }}
+          
+            aws s3 cp s3://thirdai-corp-public/ThirdAI-Platform-latest-release/${{ inputs.tarball_filename }} \$root_dir
 
             # unzip the package
-            mkdir -p /home/ubuntu/package/verbose
-            tar -xvf ${{ inputs.tarball_filename }} -C /home/ubuntu/package
+            mkdir -p \$root_dir/package/verbose
+            tar -xvf ${{ inputs.tarball_filename }} -C \$root_dir/package
 
-            cd /home/ubuntu/package
+            cd \$root_dir/package
 
             # Modify the config.yml
             yq -i '
-                .license_path = "/home/ubuntu/ndb_enterprise_license.json" |
-                .admin_mail = "${{ secrets.EMAIL }}" |
+                .license_path = "\$root_dir/ndb_enterprise_license.json" |
+                .admin_mail = "${{ inputs.email }}" |
                 .admin_username = "admin" |
-                .admin_password = "${{ secrets.PASSWORD }}" |
+                .admin_password = "${{ inputs.password }}" |
                 .genai_key = "${{ secrets.GENAI_KEY }}" |
                 .thirdai_platform_version = "${{ inputs.docker_image_version }}" |
                 .platform_image_branch = "${{ inputs.docker_image_branch_name }}" |
                 .docker_registry_password = "${{ env.docker_registry_password }}" |
                 .login_method = "postgres" |
-                .cluster_endpoint = "${{ steps.host_machine.outputs.public_ip }}" |
-                .nodes[0].private_ip = "172.31.46.139" |
-                .nodes[0].ssh_username = "ubuntu" |
+                .cluster_endpoint = "${{ steps.host_machine1.outputs.public_ip }}" |
+                .nodes[0].private_ip = "${{ steps.host_machine1.outputs.private_ip }}" |
+                .nodes[0].ssh_username = "${{ steps.host_machine1.outputs.ssh_username }}" |
                 .nodes[0].connection_type = "local" |
-                .nodes[1].private_ip = "172.31.45.183" |
-                .nodes[1].ssh_username = "ubuntu" |
+                .nodes[1].private_ip = "${{ steps.host_machine2.outputs.private_ip }}" |
+                .nodes[1].ssh_username = "${{ steps.host_machine2.outputs.ssh_username }}" |
                 .nodes[1].connection_type = "ssh"
-            '  /home/ubuntu/package/config.yml
+            '  \$root_dir/package/config.yml
 
             # verbose dir would contain the stdout and stderr of the run
-            mkdir -p /home/ubuntu/verbose/cleanup1
+            mkdir -p \$root_dir/verbose/pre_installation_cleanup
 
             # Run the cleanup script
-            ./driver.sh ./config.yml --cleanup 1> /home/ubuntu/verbose/cleanup1/cleanup.out 2> /home/ubuntu/verbose/cleanup1/cleanup.err
+            ./driver.sh ./config.yml --cleanup 1> \$root_dir/verbose/pre_installation_cleanup/cleanup.out 2> \$root_dir/verbose/pre_installation_cleanup/cleanup.err
 
-            mkdir -p /home/ubuntu/verbose/installation
+            mkdir -p \$root_dir/verbose/installation
             # Run the driver.sh script
-            ./driver.sh ./config.yml -v 1> /home/ubuntu/verbose/installation/installation.out 2> /home/ubuntu/verbose/installation/installation.err
+            ./driver.sh ./config.yml -v 1> \$root_dir/verbose/installation/installation.out 2> \$root_dir/verbose/installation/installation.err
           EOF
 
       - name: Fetch the task runner token
@@ -144,7 +220,7 @@ jobs:
           -o ServerAliveInterval=120 \
           -o ServerAliveCountMax=25 \
           -i /tmp/id_rsa \
-          ubuntu@${{ steps.host_machine.outputs.public_ip }} \
+          ${{ steps.host_machine1.outputs.ssh_username }}@${{ steps.host_machine1.outputs.public_ip }} \
           "sudo grep 'Secret ID' '/opt/thirdai_platform/nomad_data/task_runner_token.txt' | awk '{print \$NF}'")
           echo "token=$task_runner_token" >> $GITHUB_OUTPUT
       
@@ -195,10 +271,10 @@ jobs:
       - name: Run tests
         id: backend_test
         run: |
-          python3 -m headless.run_locally --base-url "http://${{ needs.setup_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ env.random_run_name }} --dag NDB --on-prem --generation
-          python3 -m headless.run_locally --base-url "http://${{ needs.setup_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ env.random_run_name }} --dag UDT
-          python3 -m headless.run_locally --base-url "http://${{ needs.setup_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ env.random_run_name }} --dag UDT_DATAGEN
-          python3 -m headless.run_locally --base-url "http://${{ needs.setup_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ env.random_run_name }} --dag Recovery_Backup
+          python3 -m headless.run_locally --base-url "http://${{ needs.setup_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ inputs.email }} --password ${{ inputs.password }} --run-name ${{ env.random_run_name }} --dag NDB --on-prem --generation
+          python3 -m headless.run_locally --base-url "http://${{ needs.setup_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ inputs.email }} --password ${{ inputs.password }} --run-name ${{ env.random_run_name }} --dag UDT
+          python3 -m headless.run_locally --base-url "http://${{ needs.setup_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ inputs.email }} --password ${{ inputs.password }} --run-name ${{ env.random_run_name }} --dag UDT_DATAGEN
+          python3 -m headless.run_locally --base-url "http://${{ needs.setup_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ inputs.email }} --password ${{ inputs.password }} --run-name ${{ env.random_run_name }} --dag Recovery_Backup
 
       - name: Test Next.js frontend
         if: always()
@@ -208,7 +284,7 @@ jobs:
           echo "Testing frontend at $BASE_URL_WITHOUT_API"
           curl -f "$BASE_URL_WITHOUT_API" || exit 1
 
-  clean_ec2_instances:
+  Stop_the_instances:
       runs-on: ubuntu-latest-8-cores
       needs: [setup_the_ec2_instances, test]
       if: always()
@@ -220,23 +296,7 @@ jobs:
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: us-east-1
         
-        - name: Create an identity file for ssh-login
-          run: |
-            echo "${{ secrets.HOST_MACHINE_PRIVATE_KEY }}" > /tmp/id_rsa
-            chmod 600 /tmp/id_rsa
-
-        - name: Run cleanup script
-          run: |
-            ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=120 -o ServerAliveCountMax=25 -i /tmp/id_rsa ubuntu@${{ needs.setup_the_ec2_instances.outputs.server_machine_public_ip }} <<EOF
-              cd /home/ubuntu/package
-
-              mkdir -p /home/ubuntu/verbose/cleanup2
-              ./driver.sh /home/ubuntu/package/config.yml --cleanup -v 1> /home/ubuntu/verbose/cleanup2/cleanup.out 2> /home/ubuntu/verbose/cleanup2/cleanup.err
-
-              rm -rf /home/ubuntu/package /home/ubuntu/${{ inputs.tarball_filename }}
-            EOF
-        
         - name: Stop the ec2-machine
           run: |
-            aws ec2 stop-instances --instance-ids i-0d7c02e319be52e71 i-066bb0f7bfb7ef7a3
+            aws ec2 stop-instances --instance-ids ${{ env.host_machine1_instance_id }} ${{ env.host_machine2_instance_id }}
       
