skeleton complete

diff --git a/.github/workflows/release-tar-ball.yml b/.github/workflows/release-tar-ball.yml
--- a/.github/workflows/release-tar-ball.yml
+++ b/.github/workflows/release-tar-ball.yml
@@ -7,7 +7,7 @@ on:
   workflow_dispatch:
     inputs:
       installer_branch_name:
-        description: "Installer branch name for the release"
+        description: "Ansible-repo branch name"
         required: true
         type: string
         default: "main"
@@ -30,10 +30,10 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      - name: Get the version of the docker images
+      - name: Get the new version of the docker images
         id: fetch_version
         run: |
-          if [[ "${{ github.event_name }}" == "release" ]]; then
+          if [[ "${{ github.event_name }}" == "release" && "${{ github.ref_name }}" == "main" ]]; then
             version=${{ github.event.release.tag_name }}
           else
             version=$(shuf -i 100-999 -n 3 | paste -sd '.')
@@ -44,7 +44,7 @@ jobs:
       - name: Set the branch name of the docker images
         id: fetch_branch_name
         run: |
-          if [[ "${{ github.event_name }}" == "release" ]]; then
+          if [[ "${{ github.event_name }}" == "release" && "${{ github.ref_name }}" == "main" ]]; then
             branch_name="release-test-main"
           else
             branch_name="installation-test-${{ github.ref_name }}"
@@ -196,16 +196,16 @@ jobs:
       - name: Package platform, model, driver script, config, and README into tarball
         id: online_pack
         run: |
-          name="thirdai-platform-package-${{ needs.build_docker_images.outputs.docker_image_branch_name }}-${{ needs.build_docker_images.outputs.version }}.tar.gz"
-          echo "::set-output name=name::$name"
-          tar -czvf $name ./platform ./gen-ai-models ./driver.sh ./config.yml ./README.md
+          tarfile_name="thirdai-platform-package-${{ needs.build_docker_images.outputs.docker_image_branch_name }}-${{ needs.build_docker_images.outputs.version }}.tar.gz"
+          echo "::set-output name=name::$tarfile_name"
+          tar -czvf $tarfile_name ./platform ./gen-ai-models ./driver.sh ./config.yml ./README.md
 
       - name: Package Docker images, platform, model, driver script, config, and README into tarball
         id: offline_pack
         run: |
-          name="thirdai-platform-package-offline-${{ needs.build_docker_images.outputs.docker_image_branch_name }}-${{ needs.build_docker_images.outputs.version }}.tar.gz"
-          echo "::set-output name=name::$name"
-          tar -czvf $name ./platform ./docker_images-${{ needs.build_docker_images.outputs.version }} ./driver.sh ./config.yml ./README.md ./gen-ai-models
+          tarfile_name="thirdai-platform-package-offline-${{ needs.build_docker_images.outputs.docker_image_branch_name }}-${{ needs.build_docker_images.outputs.version }}.tar.gz"
+          echo "::set-output name=name::$tarfile_name"
+          tar -czvf $tarfile_name ./platform ./docker_images-${{ needs.build_docker_images.outputs.version }} ./driver.sh ./config.yml ./README.md ./gen-ai-models
 
       - name: Upload online platform package to S3
         run: |
@@ -242,7 +242,7 @@ jobs:
       # These instances already have the aws configured to pull thirdai-packages from the s3 bucket
       - name: start the ec2-instance
         run: |
-          aws ec2 start-instances --instance-ids i-0fcca07a398bcfc8f i-<another-instance>
+          aws ec2 start-instances --instance-ids i-08bfe31f7665561c5 i-00c741703fbf15a4d
       
       - name: Wait for EC2 to be running
         run: |
@@ -253,7 +253,7 @@ jobs:
         id: host_machine
         run: |
           PUBLIC_IP=$(aws ec2 describe-instances \
-            --instance-ids i-0fcca07a398bcfc8f \
+            --instance-ids i-08bfe31f7665561c5 \
             --query "Reservations[0].Instances[0].PublicIpAddress" \
             --output text)
           echo "::set-ouput name=public_ip::$PUBLIC_IP"
@@ -269,7 +269,7 @@ jobs:
       
       - name: Download the package and run driver.sh
         run: |
-          ssh -o StrictHostKeyChecking=no ubuntu@${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }} <<<EOF
+          ssh -o StrictHostKeyChecking=no ubuntu@$${{ steps.host_machine.outputs.public_ip }}  <<<EOF
             aws s3 cp s3://thirdai-corp-public/ThirdAI-Platform-latest-release/${{ needs.package.outputs.online_package_name }} .
 
             # unzip the package
@@ -287,11 +287,11 @@ jobs:
               .platform_branch = "${{ needs.build_docker_images.outputs.docker_image_branch_name }}" |
               .docker_registry_password = "${{ needs.build_docker_images.outputs.docker_registy_password }}" |
               .login_method = "postgres" |
-              .nodes[0].public_ip = "${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}" |
-              .nodes[0].private_ip = "12.12.12.12" |
+              .nodes[0].public_ip = "${{ steps.host_machine.outputs.public_ip }}" |
+              .nodes[0].private_ip = "172.31.17.228" |
               .nodes[0].ssh_username = "ubuntu" |
               .nodes[0].connection_type = "local" |
-              .nodes[1].private_ip = "13.13.13.13" |
+              .nodes[1].private_ip = "172.31.31.123" |
               .nodes[1].ssh_username = "ubuntu" |
               .nodes[1].connection_type = "ssh" |
             '  ./package/config.yml
@@ -303,56 +303,59 @@ jobs:
       - name: Wait for 7 minutes to let the model_bazaar get started
         run: sleep $((7 * 60))
 
-  test:
-    strategy:
-      fail-fast: false
-    runs-on: ubuntu-latest
-    needs: [build_docker_images, package, start_the_ec2_instances]
+  # test:
+  #   strategy:
+  #     fail-fast: false
+  #   runs-on: ubuntu-latest
+  #   needs: [start_the_ec2_instances]
+  #   outputs:
+  #     exit_code: ${{ steps.backend_test_status.outputs.exit_code }}
 
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v2
+  #   steps:
+  #     - name: Checkout the repository
+  #       uses: actions/checkout@v2
       
-      - name: Set up Python 3.9
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.9
+  #     - name: Set up Python 3.9
+  #       uses: actions/setup-python@v2
+  #       with:
+  #         python-version: 3.9
 
-      - name: Install requirements
-        run: |
-          cd headless
-          pip install -r requirements.txt
+  #     - name: Install requirements
+  #       run: |
+  #         cd headless
+  #         pip install -r requirements.txt
 
-      - name: Env variables
-        run: |
-          echo "SHARE_DIR=$HOME/nfs/dir" >> $GITHUB_ENV
-          echo "GENAI_KEY=${{ secrets.GENAI_KEY }}" >> $GITHUB_ENV
-          mkdir -p ${{ env.SHARE_DIR }}
+  #     - name: Env variables
+  #       run: |
+  #         echo "SHARE_DIR=$HOME/nfs/dir" >> $GITHUB_ENV
+  #         echo "GENAI_KEY=${{ secrets.GENAI_KEY }}" >> $GITHUB_ENV
+  #         mkdir -p ${{ env.SHARE_DIR }}
 
-      - name: Generate random run name
-        id: random-run-name
-        run: |
-          echo "::set-output name=name::test_$(python3 -c "import secrets; print(secrets.token_urlsafe(8))")"
+  #     - name: Generate random run name
+  #       id: random-run-name
+  #       run: |
+  #         echo "::set-output name=name::test_$(python3 -c "import secrets; print(secrets.token_urlsafe(8))")"
       
-      - name: Run tests
-        id: backend_test_status
-        run: |
-          python3 -m headless.run_locally --base-url "http://${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag NDB --on-prem --generation
-          python3 -m headless.run_locally --base-url "http://${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag UDT
-          python3 -m headless.run_locally --base-url "http://${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag UDT_DATAGEN
-          python3 -m headless.run_locally --base-url "http://${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag Recovery_Backup
-      
-      - name: Test Next.js frontend
-        if: always()
-        id: frontend_test_status
-        run: |
-          BASE_URL_WITHOUT_API=$(echo "${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}" | sed 's/\/api\/\?$//')
-          echo "Testing frontend at $BASE_URL_WITHOUT_API"
-          curl -f "$BASE_URL_WITHOUT_API" || exit 1
+  #     - name: Run tests
+  #       id: backend_test_status
+  #       run: |
+  #         python3 -m headless.run_locally --base-url "http://${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag NDB --on-prem --generation
+  #         python3 -m headless.run_locally --base-url "http://${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag UDT
+  #         python3 -m headless.run_locally --base-url "http://${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag UDT_DATAGEN
+  #         python3 -m headless.run_locally --base-url "http://${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}/api/" --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }} --run-name ${{ steps.random-run-name.outputs.name }} --dag Recovery_Backup
+  #         echo "::set-output name=exit_code::$?"
+
+  #     - name: Test Next.js frontend
+  #       if: always()
+  #       id: frontend_test_status
+  #       run: |
+  #         BASE_URL_WITHOUT_API=$(echo "${{ needs.start_the_ec2_instances.outputs.server_machine_public_ip }}" | sed 's/\/api\/\?$//')
+  #         echo "Testing frontend at $BASE_URL_WITHOUT_API"
+  #         curl -f "$BASE_URL_WITHOUT_API" || exit 1
         
   cleanup:
     runs-on: ubuntu-latest
-    needs: [build_docker_images, package, start_the_ec2_instances, test]
+    needs: [build_docker_images, package, start_the_ec2_instances]
     if: always()
     steps:
       - name: Install AWS CLI
@@ -381,8 +384,24 @@ jobs:
       
       - name: Stop the ec2-machine
         run: |
-          aws ec2 stop-instances --instance-ids  i-0fcca07a398bcfc8f i-<another-instance>
+          aws ec2 stop-instances --instance-ids i-08bfe31f7665561c5 i-00c741703fbf15a4d
       
-      - 
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Set up Python 3.9
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.9
+  
+      - name: Delete docker images
+        if: github.event_name != 'release'
+        run: |
+          cd release
+          pip install -r requirements.txt
+          version="${{ needs.build_docker_images.outputs.version }}"
+          echo "Deleting Docker images for branch ${{ needs.build_docker_images.outputs.docker_image_branch_name }} with version: $version"
+          python3 docker_remove.py -b ${{ needs.build_docker_images.outputs.docker_image_branch_name }} --version "$version" --client_id ${{ secrets.APPLICATION_ID }} --tenant_id ${{ secrets.TENANT_ID }} --secret ${{ secrets.SECRET }} --config config.yaml
+
 
   
